version: '3'
services:
  bmsapp:
    depends_on:
      - bmsmysql
    networks:
      - bmsnet
    image: ${BMS_IMG_URI:?err}:${BMS_RELEASE:?err}
    ports:
      - "80:8080"
    restart: always
    environment:
      - BMS_CROPS=${BMS_CROPS:?err}
    volumes:
      - mysqldata:/var/lib/mysql
    links:
      - bmsmysql
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  bmsmysql:
    image: mysql:5.6
    ports:
       - "3307:3306"
    networks:
      - bmsnet
    volumes:
         - mysqldata:/var/lib/mysql
         - ./mysql/conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ulimits:
       nofile:
         soft: 20000
         hard: 40000
    environment:
      MYSQL_ROOT_PASSWORD: ${BMS_DB_PASS:?err}

volumes:
  mysqldata:
    external: false

networks:
  bmsnet:
    driver: bridge
