version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxycerts:/etc/nginx/certs
      - proxyvhost:/etc/nginx/vhost.d
      - proxyhtml:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - bmsnet
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${BMS_SSL_EMAIL:-greg@leafnode.io}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxycerts:/etc/nginx/certs
      - proxyvhost:/etc/nginx/vhost.d
      - proxyhtml:/usr/share/nginx/html
    networks:
      - bmsnet
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
        
  bmsapp:
    depends_on:
      - bmsmysql
    networks:
      - bmsnet
    image: ${BMS_IMG_URI:?err}:${BMS_RELEASE:?err}
    ports:
      - "8080:8080"
    restart: always
    environment:
      - VIRTUAL_HOST=${BMS_SSL_HOST:-bmsdock.leafnode.io}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${BMS_SSL_HOST:-bmsdock.leafnode.io}
      - LETSENCRYPT_EMAIL=${BMS_SSL_EMAIL:-greg@leafnode.io}
      - BMS_SCHEME=${BMS_SCHEME:-http}
      - BMS_PORT=${BMS_PORT:-443}
      - BMS_CROPS=${BMS_CROPS:?err}
    volumes:
      - mysqldata:/var/lib/mysql
    links:
      - bmsmysql
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  bmsmysql:
    image: mysql:5.6
    ports:
       - "3307:3306"
    networks:
      - bmsnet
    volumes:
         - mysqldata:/var/lib/mysql
         - ./mysql/conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ulimits:
       nofile:
         soft: 20000
         hard: 40000
    environment:
      MYSQL_ROOT_PASSWORD: ${BMS_DB_PASS:?err}

volumes:
  mysqldata:
  proxycerts:
  proxyvhost:
  proxyhtml:

networks:
  bmsnet:
    driver: bridge