version: '3'
services:
  bmsapp:
    depends_on:
      - bmsmysql-1
    image: ${BMS_IMG_URI:?err}:${BMS_RELEASE:?err}
    ports:
      - "18080:8080"
    restart: always
    environment:
      - VIRTUAL_HOST=${BMS_SSL_HOST:-bmsdock.leafnode.io}
      - VIRTUAL_PORT=18080
      - LETSENCRYPT_HOST=${BMS_SSL_HOST:-bmsdock.leafnode.io}
      - LETSENCRYPT_EMAIL=${BMS_SSL_EMAIL:-leafnodedev@leafnode.io}
      - BMS_SCHEME=${BMS_SCHEME:-https}
      - BMS_PORT=${BMS_PORT:-443}
      - BMS_CROPS=${BMS_CROPS:?err}
      - BMS_DB_HOST=${BMS_DB_HOST:?err}
      - BMS_DB_PASSWORD=${BMS_DB_PASS:?err}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./logs:/usr/local/tomcat/logs
      - ./config:/bms/BMSConfig/bmsdocker
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  bmsmysql-1:
    image: mysql:5.6
    ports:
       - "13306:3306"
    volumes:
         - mysqldata:/var/lib/mysql
         - ./mysql/conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ulimits:
       nofile:
         soft: 20000
         hard: 40000
    environment:
      MYSQL_ROOT_PASSWORD: ${BMS_DB_PASS:?err}

volumes:
  mysqldata:

networks:
  default:
    external:
      name: proxy_bmsnet