version: '3'
services:
  bmsapp:
    depends_on:
      - bmsmysql-1
    image: ${BMS_IMG_URI:?err}:${BMS_RELEASE:?err}
    ports:
      - "18080:8080"
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-}
      - SFTP_HOST=${SFTP_HOST:-}
      - SFTP_USERNAME=${SFTP_USERNAME:-}
      - SFTP_PASSWORD=${SFTP_PASSWORD:-}
      - SFTP_PRIVATE_KEY_PATH=${SFTP_PRIVATE_KEY_PATH:-}
      - VIRTUAL_HOST=${BMS_SSL_HOST:-bmsdock.leafnode.io}
      - VIRTUAL_PORT=18080
      - LETSENCRYPT_HOST=${BMS_SSL_HOST:-bmsdock.leafnode.io}
      - LETSENCRYPT_EMAIL=${BMS_SSL_EMAIL:-leafnodedev@leafnode.io}
      - BMS_SCHEME=${BMS_SCHEME:-https}
      - BMS_PORT=${BMS_PORT:-443}
      - BMS_CROPS=${BMS_CROPS:?err}
      - BMS_DB_HOST=${BMS_DB_HOST:?err}
      - BMS_DB_PASSWORD=${BMS_DB_PASS:?err}
      - CATALINA_OPTS=-javaagent:/opt/spring-instrument-4.1.6.RELEASE.jar
      - JAVA_OPTS=-server -Xms${BMS_MEMORY:?err} -Xmx${BMS_MEMORY:?err} -XX:+CMSClassUnloadingEnabled ${LIQUIBASE_PARAM}
      - BASE_URL=${BASE_URL:-}
      - SECURITY_2FA_ENABLED=${SECURITY_2FA_ENABLED:-true}
      - SECURITY_2FA_ENFORCE_OTP_ON_UNKNOWN_DEVICE=${SECURITY_2FA_ENFORCE_OTP_ON_UNKNOWN_DEVICE:-false}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./logs:/usr/local/tomcat/logs
      - ./config:/bms/BMSConfig/bmsdocker
      - ./custom:/custom
    entrypoint: ['/custom/copy.sh']
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  bmsmysql-1:
    image: mysql:5.7.41
    ports:
       - "13306:3306"
    volumes:
         - mysqldata:/var/lib/mysql
         - ./mysql/conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ulimits:
       nofile:
         soft: 20000
         hard: 40000
    environment:
      MYSQL_ROOT_PASSWORD: ${BMS_DB_PASS:?err}

volumes:
  mysqldata:

networks:
  default:
    external:
      name: proxy_bmsnet
